# Generated by Django 5.2.4 on 2025-07-20 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('school_code', models.CharField(max_length=100, unique=True)),
                ('manager_personal_code', models.CharField(max_length=100, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=100, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='management.school')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_family', models.CharField(max_length=100)),
                ('student_national_code', models.CharField(max_length=100, unique=True)),
                ('student_password', models.CharField(max_length=100)),
                ('student_phone_number', models.CharField(max_length=100, unique=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='management.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='management.school')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_family', models.CharField(max_length=100)),
                ('teacher_national_code', models.CharField(max_length=100, unique=True)),
                ('teacher_password', models.CharField(max_length=100)),
                ('lesson', models.CharField(max_length=100)),
                ('classes', models.ManyToManyField(related_name='teachers', to='management.class')),
                ('schools', models.ManyToManyField(related_name='teachers', to='management.school')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
