class Config:
    SQLALCHEMY_DATABASE_URI = 'mysql://root:sapprogram2583@185.4.28.110:5000/sap'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_POOL_SIZE = 10
    SQLALCHEMY_MAX_OVERFLOW = 20
    SQLALCHEMY_POOL_TIMEOUT = 30
    SQLALCHEMY_POOL_RECYCLE = 1800
    SECRET_KEY = 'your_secret_key'
    COMPRESS_LEVEL = 9